BackendMainLogic/WebAppMVC/Controllers/AuthController.cs
using Application.Users.Commands.CreateUser;
using Application.Users.Queries.FindUser;
using Domain.TelegramBotEntities;
using MediatR;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebAppMVC.Models;

namespace WebAppMVC.Controllers;

public class AuthController : Controller
{
    private readonly IMediator _mediator;
    private readonly SignInManager<AppUser> _signInManager;
    private readonly UserManager<AppUser> _userManager;

    public AuthController(IMediator mediator, SignInManager<AppUser> signInManager, UserManager<AppUser> userManager)
    {
        _mediator = mediator;
        _signInManager = signInManager;
        _userManager = userManager;
    }

    [HttpGet]
    public IActionResult Registration()
    {
        return View();
    }
    
    [HttpPost]
    public async Task<IActionResult> Registration([FromForm] RegistrationViewModel registrationViewModel)
    {
        var newUserId = await _mediator.Send(new CreateUserCommand()
        {
            Username = registrationViewModel.UserName,
            Age = registrationViewModel.Age,
            Password = registrationViewModel.Password
        });
        
        if (!string.IsNullOrEmpty(newUserId.ToString()))
        {
            await _signInManager.SignInAsync(await _userManager.FindByIdAsync(newUserId.ToString()), 
                false);
            
            return RedirectToAction("Main", "Home");
        }

        return View(registrationViewModel);
    }

    [HttpGet]
    public IActionResult Login()
    {
        return View();
    }
    
    [HttpPost]
    public async Task<IActionResult> Login([FromForm] LoginViewModel loginViewModel)
    {
        var user = await _mediator.Send(new FindUserQuery(loginViewModel.UserName));

        if (user is not null && _userManager.PasswordHasher.VerifyHashedPassword(user, user.PasswordHash, loginViewModel.Password) 
            == PasswordVerificationResult.Success)
        {
            await _signInManager.SignInAsync(await _userManager.FindByIdAsync(user.Id),false);

            return RedirectToAction("Main", "Home");
        }

        return View(loginViewModel);
    }

    [HttpGet]
    public async Task<IActionResult> Logout()
    {
        await _signInManager.SignOutAsync();

        return RedirectToAction("Login");
    }
}

BackendMainLogic/WebAppMVC/Controllers/NutrientsPlanController.cs
using Application.TelegramBot.Commands.UpdateUserNutrientsPlan;
using Domain.TelegramBotEntities.NutrientsPlan;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebAppMVC.Controllers;

[Authorize(Roles = "User")]
public class NutrientsPlanController : Controller
{
    private readonly IMediator _mediator;

    public NutrientsPlanController(IMediator mediator)
    {
        _mediator = mediator;
    }
    
    [HttpGet]
    public IActionResult NutrientsPlanForm()
    {
        return View("_NutrientsPlanFormPartial");
    }
    
    [HttpPost]
    public async Task<ViewResult> UpdateNutrientsPlan([FromForm] NutrientsPlanFormDto nutrientsPlanFormViewModel)
    {
        if (!ModelState.IsValid)
        {
            return View("_ResponseMessageComponent", string.Join("; ", ModelState.Values
                .SelectMany(x => x.Errors)
                .Select(x => x.ErrorMessage)));
        }
        
        var username = User.Identity?.Name;

        var result = await _mediator.Send(new UpdateUserNutrientsPlanCommand(username!, new NutrientsPlanFormDto
        {
            CaloriesMin = nutrientsPlanFormViewModel.CaloriesMin,
            CaloriesMax = nutrientsPlanFormViewModel.CaloriesMax,
            CarbohydratesMin = nutrientsPlanFormViewModel.CarbohydratesMin,
            CarbohydratesMax = nutrientsPlanFormViewModel.CarbohydratesMax,
            ProteinMin = nutrientsPlanFormViewModel.ProteinMin,
            ProteinMax = nutrientsPlanFormViewModel.ProteinMax,
            FatMin = nutrientsPlanFormViewModel.FatMin,
            FatMax = nutrientsPlanFormViewModel.FatMax
        }));

        return View("_ResponseMessageComponent", result);
    }
}

BackendMainLogic/WebAppMVC/Controllers/RecipesController.cs
using System.Text.Json;
using Application.TelegramBot.Commands.AddAllLikedRecipesAsMeal;
using Application.TelegramBot.Commands.AddAllRecipesAsPartOfMeal;
using Application.TelegramBot.Commands.AddRecipeAsPartOfMeal;
using Application.TelegramBot.Commands.AddRecipesToUser;
using Application.TelegramBot.Commands.AddRecipeToUser;
using Application.TelegramBot.Commands.ClearLikedRecipesList;
using Application.TelegramBot.Commands.ClearRecipesAsPartOfMeal;
using Application.TelegramBot.Commands.RemoveRecipeFromLikedList;
using Application.TelegramBot.Commands.RemoveRecipeFromTheMeal;
using Application.TelegramBot.Queries.GetMealPlanForUser;
using Application.TelegramBot.Queries.GetRecipesAsPartOfMeal;
using Application.TelegramBot.Queries.GetRecipesByIngredients;
using Application.TelegramBot.Queries.GetRecipesByNutrients;
using Application.TelegramBot.Queries.GetUserRecipeList;
using Domain.TelegramBotEntities;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebAppMVC.Models;

namespace WebAppMVC.Controllers;

[Authorize(Roles = "User")]
public class RecipesController : Controller
{
    private readonly IMediator _mediator;

    public RecipesController(IMediator mediator)
    {
        _mediator = mediator;
    }
    [HttpGet]
    public async Task<IActionResult> ShowRecipes(int pageNumber = 1, bool isMealPlan = false)
    {
        var username = User.Identity?.Name;
        
        if (HttpContext.Session.GetString("CurrentRecipes") is null)
        {
            HttpContext.Session.SetString("CurrentRecipes", JsonSerializer
                .Serialize(await _mediator.Send(new GetUserRecipeListQuery(username!))));
        }

        if (HttpContext.Session.GetString("Nutrients") is null)
        {
            HttpContext.Session.SetString("Nutrients",JsonSerializer.Serialize(new NutrientViewDto()));
        }

        var recipes = JsonSerializer.Deserialize<List<Recipe>>(HttpContext.Session.GetString("CurrentRecipes") ?? throw new InvalidOperationException());

        var nutrients = JsonSerializer.Deserialize<NutrientViewDto>(HttpContext.Session.GetString("Nutrients") ?? throw new InvalidOperationException());

        return View("RecipesCarousel", new RecipesCarouselViewModel
        {
            Recipes = recipes!.Skip((pageNumber - 1) * 3).Take(3).ToList(),
            NutrientViewDto = nutrients,
            MaxRecipesPerPage = 3,
            CurrentPageNumber = pageNumber,
            TotalRecipesCount = recipes!.Count,
            IsMealPlan = isMealPlan
        });
    }

    [HttpGet]
    public async Task<IActionResult> LikedRecipes()
    {
        var username = User.Identity?.Name;
        
        var result = await _mediator.Send(new GetUserRecipeListQuery(username!));
        
        HttpContext.Session.SetString("CurrentRecipes", JsonSerializer.Serialize(result));

        return await ShowRecipes();
    }

    [HttpGet]
    public async Task<IActionResult> AddRecipeToUser([FromQuery] string recipeId)
    {
        var username = User.Identity?.Name;
        
        var result = await _mediator.Send(new AddRecipeToUserCommand(username!, recipeId));

        return View("_ResponseMessageComponent", result);
    }
    
    [HttpGet]
    public async Task<IActionResult> RecipesByNutrients()
    {
        var username = User.Identity?.Name;
        
        var result = await _mediator.Send(new GetRecipesByNutrientsQuery(username!));

        HttpContext.Session.SetString("CurrentRecipes", JsonSerializer.Serialize(result));

        return await ShowRecipes();
    }

    [HttpGet]
    public async Task<IActionResult> AddRecipeAsPartOfMeal([FromQuery] string recipeId)
    {
        var username = User.Identity?.Name;
        
        var result = await _mediator.Send(new AddRecipeAsPartOfMealCommand(username!, recipeId));

        return View("_ResponseMessageComponent", result);
    }
    
    [HttpGet]
    public async Task<IActionResult> RemoveRecipeFromTheMeal([FromQuery] string recipeId)
    {
        var username = User.Identity?.Name;
        
        var result = await _mediator.Send(new RemoveRecipeFromTheMealCommand(username!, recipeId));

        return View("_ResponseMessageComponent", result);
    }
    
    [HttpGet]
    public async Task<IActionResult> RemoveRecipeFromLikedList([FromQuery] string recipeId)
    {
        var username = User.Identity?.Name;
        
        var result = await _mediator.Send(new RemoveRecipeFromLikedListCommand(username!, recipeId));

        return View("_ResponseMessageComponent", result);
    }

    [HttpGet]
    public async Task<IActionResult> ClearLikedRecipesList()
    {
        var username = User.Identity?.Name;
        
        var result = await _mediator.Send(new ClearLikedRecipesListCommand(username!));

        return View("_ResponseMessageComponent", result);
    }
    
    [HttpGet]
    public async Task<IActionResult> ClearRecipesAsPartOfMeal()
    {
        var username = User.Identity?.Name;
        
        var result = await _mediator.Send(new ClearRecipesAsPartOfMealCommand(username!));

        return View("_ResponseMessageComponent", result);
    }

    [HttpGet]
    public async Task<IActionResult> RecipesAsPartOfMeal()
    {
        var username = User.Identity?.Name;
        
        var result = await _mediator.Send(new GetRecipesAsPartOfMealQuery(username!));

        HttpContext.Session.SetString("CurrentRecipes",JsonSerializer.Serialize(result));

        return await ShowRecipes();
    }

    [HttpGet]
    public async Task<IActionResult> MealPlanForUser()
    {
        var username = User.Identity?.Name;
        
        var result = await _mediator.Send(new GetMealPlanForUserQuery(username!));
        
        HttpContext.Session.SetString("CurrentRecipes",JsonSerializer.Serialize(result.Item1));
        
        HttpContext.Session.SetString("Nutrients",JsonSerializer.Serialize(result.Item2));

        return await ShowRecipes(isMealPlan:true);
    }

    [HttpGet]
    public async Task<IActionResult> AddAllLikedRecipesAsMeal()
    {
        var username = User.Identity?.Name;
        
        var result = await _mediator.Send(new AddAllLikedRecipesAsMealCommand(username!));

        return View("_ResponseMessageComponent", result);
    }
    
    [HttpGet]
    public async Task<IActionResult> AddAllRecipesAsPartOfMeal()
    {
        var username = User.Identity?.Name;
        
        var result = await _mediator.Send(new AddAllRecipesAsPartOfMealCommand(username!));

        return View("_ResponseMessageComponent", result);
    }
    
    [HttpPost]
    public async Task<IActionResult> RecipesByIngredients([FromForm] string newValue)
    {
        var username = User.Identity?.Name;
        
        var result = await _mediator.Send(new GetRecipesByIngredientsQuery(username!, newValue));

        HttpContext.Session.SetString("CurrentRecipes", JsonSerializer.Serialize(result));

        return await ShowRecipes();
    }
    
    [HttpPost]
    public async Task<string> AddRecipesToUser([FromBody] string recipeIds)
    {
        var username = User.Identity?.Name;
        
        var recipeIdsList = JsonSerializer.Deserialize<List<string>>(recipeIds);

        return await _mediator.Send(new AddRecipesToUserCommand(username!, recipeIdsList!));
    }
}

BackendMainLogic/WebAppMVC/Views/Shared/HeaderNavbar.cshtml
<div>
    <div class="antialiased bg-gray-100 dark-mode:bg-gray-900">
        <div class="w-full text-gray-700 bg-white dark-mode:text-gray-200 dark-mode:bg-gray-800">
            <div x-data="{ open: true }" class="flex flex-col max-w-screen-xl px-4 mx-auto md:items-center md:justify-between md:flex-row md:px-6 lg:px-8">
                <div class="flex flex-row items-center justify-between p-4">
                    <a href="#" class="text-lg font-semibold tracking-widest text-gray-900 uppercase rounded-lg dark-mode:text-white focus:outline-none focus:shadow-outline">Flowtrail UI</a>
                    <button class="rounded-lg md:hidden focus:outline-none focus:shadow-outline" @@click="open = !open">
                        <svg fill="currentColor" viewBox="0 0 20 20" class="w-6 h-6">
                            <path x-show="!open" fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM9 15a1 1 0 011-1h6a1 1 0 110 2h-6a1 1 0 01-1-1z" clip-rule="evenodd"></path>
                            <path x-show="open" fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                        </svg>
                    </button>
                </div>
                <nav :class="{'flex': open, 'hidden': !open}" class="flex-col flex-grow hidden pb-4 md:pb-0 md:flex md:justify-end md:flex-row">
                    <a class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="#">Blog</a>
                    <a class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="#">Portfolio</a>
                    <a class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="#">About</a>
                    <a class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="#">Contact</a>
                    <a asp-action="Logout" asp-controller="Auth" class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline">Logout</a>
                </nav>
            </div>
        </div>
    </div>
</div>

BackendMainLogic/WebAppMVC/Views/Shared/_Footer.cshtml
<footer class="bg-blueGray-50 mt-2 fixed bottom-0 w-full">
    <div class="container mx-auto py-2">
        <div class="flex flex-wrap items-center md:justify-between justify-center">
            <div class="w-full md:w-6/12 px-2 mx-auto text-center">
                <div class="text-sm text-blueGray-500 font-semibold py-1">
                    xdzz-cyber 2023
                </div>
            </div>
        </div>
    </div>
</footer>

BackendMainLogic/WebAppMVC/Views/Shared/_HeaderNavbarPartial.cshtml
<div>
    <div class="antialiased bg-gray-100 dark-mode:bg-gray-900">
        <div class="w-full text-gray-700 bg-white dark-mode:text-gray-200 dark-mode:bg-gray-800">
            <div x-data="{ open: true }" class="flex flex-col max-w-screen-xl px-4 mx-auto md:items-center md:justify-between md:flex-row md:px-6 lg:px-8">
                <div class="flex flex-row items-center justify-between p-4">
                    <a asp-controller="Home" asp-action="Main" class="text-lg font-semibold tracking-widest text-gray-900 uppercase rounded-lg dark-mode:text-white focus:outline-none focus:shadow-outline">Nutrients app</a>
                    <button class="rounded-lg md:hidden focus:outline-none focus:shadow-outline" @@click="open = !open">
                        <svg fill="currentColor" viewBox="0 0 20 20" class="w-6 h-6">
                            <path x-show="!open" fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM9 15a1 1 0 011-1h6a1 1 0 110 2h-6a1 1 0 01-1-1z" clip-rule="evenodd"></path>
                            <path x-show="open" fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                        </svg>
                    </button>
                </div>
                <nav :class="{'flex': open, 'hidden': !open}" class="flex-col flex-grow hidden pb-4 md:pb-0 md:flex md:justify-end md:flex-row">
                    <a class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" 
                       asp-action="ShowRecipes" asp-controller="Recipes">Recipes</a>
                    <a class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" 
                       asp-action="LikedRecipes" asp-controller="Recipes">Liked recipes</a>
                    <a class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" 
                                           asp-action="About" asp-controller="Home">About</a>
                    <a class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" 
                                           asp-action="RecipesAsPartOfMeal" asp-controller="Recipes">Get meals</a>
                    <a class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" 
                                           asp-action="MealPlanForUser" asp-controller="Recipes">Get Meal plan</a>
                    <a asp-action="Logout" asp-controller="Auth" class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline">Logout</a>
                </nav>
            </div>
        </div>
    </div>
</div>

BackendMainLogic/WebAppMVC/Views/Shared/_NutrientsPlanFormPartial.cshtml
@{
    Layout = "_Layout";
}

@model Domain.TelegramBotEntities.NutrientsPlan.NutrientsPlanFormDto

<partial name="_HeaderNavbarPartial"/>
<div class="flex items-center justify-center p-12">
  <!-- Author: FormBold Team -->
  <!-- Learn More: https://formbold.com -->
  <div class="mx-auto w-full max-w-[550px]">
    <form asp-action="UpdateNutrientsPlan" asp-controller="NutrientsPlan" method="POST">
        <div class="-mx-3 flex flex-row">
            <div class="px-3 w-1/2">
                <div class="mb-5">
                    <label for="fatMin" class="mb-3 block text-base font-medium text-[#07074D]">
                        Fat min value
                    </label>
                    <input
                        min="0"
                        asp-for="FatMin"
                        id="fatMin"
                        class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                    />
                </div>
            </div>
            <div class="px-3 w-1/2">
                <div class="mb-5">
                    <label for="fatMax" class="mb-3 block text-base font-medium text-[#07074D]">
                        Fat max value
                    </label>
                    <input
                        min="0"
                        asp-for="FatMax"
                        id="fatMax"
                        class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                    />
                </div>
            </div>
        </div>
        <div class="-mx-3 flex flex-row">
            <div class="px-3 w-1/2">
                <div class="mb-5">
                    <label for="carbohydratesMin" class="mb-3 block text-base font-medium text-[#07074D]">
                        Carbohydrates min
                    </label>
                    <input
                        min="0"
                        asp-for="CarbohydratesMin"
                        id="carbohydratesMin"
                        class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                    />
                </div>
            </div>
            <div class="px-3 w-1/2">
                <div class="mb-5">
                    <label for="carbohydratesMax" class="mb-3 block text-base font-medium text-[#07074D]">
                        Carbohydrates max
                    </label>
                    <input
                        min="0"
                        asp-for="CarbohydratesMax"
                        id="carbohydratesMax"
                        class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                    />
                </div>
            </div>
        </div>
        <div class="-mx-3 flex flex-row">
            <div class="px-3 w-1/2">
                <div class="mb-5">
                    <label for="proteinMin" class="mb-3 block text-base font-medium text-[#07074D]">
                        Protein min
                    </label>
                    <input
                        min="0"
                        asp-for="ProteinMin"
                        id="proteinMin"
                        class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                    />
                </div>
            </div>
            <div class="px-3 w-1/2">
                <div class="mb-5">
                    <label for="proteinMax" class="mb-3 block text-base font-medium text-[#07074D]">
                        Protein max
                    </label>
                    <input
                        min="0"
                        asp-for="ProteinMax"
                        id="proteinMax"
                        class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                    />
                </div>
            </div>
        </div>
        <div class="-mx-3 flex flex-row">
                <div class="w-full px-3 sm:w-1/2">
                  <div class="mb-5">
                    <label for="caloriesMin" class="mb-3 block text-base font-medium text-[#07074D]">
                      Calories min
                    </label>
                      <input
                          min="0"
                      asp-for="CaloriesMin"
                      id="caloriesMin"
                      class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                    />
                  </div>
                </div>
                <div class="w-full px-3 sm:w-1/2">
                  <div class="mb-5">
                    <label for="caloriesMax" class="mb-3 block text-base font-medium text-[#07074D]">
                      Calories max
                    </label>
                      <input
                          min="0"
                      asp-for="CaloriesMax"
                      id="caloriesMax"
                      class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                    />
                  </div>
                </div>
              </div>
        <div class="flex justify-center mt-4">
            <button class="bg-pink-500 shadow-form text-white rounded-md bg-[#6A64F1] py-3 px-8 text-center text-base font-semibold outline-none">
                Submit
            </button>
        </div>
        <div asp-validation-summary="All" class="text-red-400"></div>
    </form>
  </div>
</div>
<partial name="_Footer"/>